### ISSUE TITLE
Ball on screen

### ISSUE THREAD

**Issue by Coder7575** [GDevelopApp/GDevelop-website-showcase#10]
![QniPxk](https://user-images.githubusercontent.com/77971713/105717554-48e13400-5f46-11eb-87a8-b24062b75142.jpg)
![Edtf67](https://user-images.githubusercontent.com/77971713/105717595-54ccf600-5f46-11eb-85b2-395ecd68c6e1.jpg)

## Screenshots

- Insert one or more screenshots. Make sure they are extra pretty! :)

## Name, links and details

- Your name: Coder75
- Your game name: Ball on screen
- Description of the game in a few sentences: Push the ball in a direction by touching it.The objective of the game is that the ball should not cross the game screen boundaries by giving it different directions.If the ball crosses the game screen boundary the game gets finished and the time from the first touch to the ball till the ball crosses the screen boundary is displayed.The time is displayed in seconds.Try to play for a longer time.The highest time can be seen from the HIGHEST TIME option.

It is a fast game.

Strategy-

Touch the circumference of the ball.

Don't give heavy touches to the ball.

Try to play end to end.
- Links to download, buy or play to the game: https://coder75.itch.io/ball-on-screen

**Comment by 4ian** [comment]
Hello! I've made a form now to add games to the showcase, could you fill it up with your game description and images? It's here: https://docs.google.com/forms/d/e/1FAIpQLSfjiOnkbODuPifSGuzxYY61vB5kyMWdTZSSqkJsv3H6ePRTQA/viewform?usp=sf_link

Thanks! :)
