### ISSUE TITLE
sprite size

### ISSUE THREAD

**Issue by malekelsady** [GDevelopApp/GDevelop-website-showcase#11]
my name is Malek-Elsady and this is my fourth game Sprite Size where you have to stretch your sprite to reach places you could not before while avoiding falling off the edge
https://malek-elsady.itch.io/sprite-size
![Screenshot (247)](https://user-images.githubusercontent.com/77232429/106361959-db0f8080-6328-11eb-8d66-4c43a78dcc9a.png)
![Screenshot (248)](https://user-images.githubusercontent.com/77232429/106361960-dc40ad80-6328-11eb-85b3-0cf691a57d02.png)
![Uploading Screenshot (250).png…]()
![New Piskel-1 png (46)-1 png](https://user-images.githubusercontent.com/77232429/106326914-f5445280-6285-11eb-82ff-2fe0502c6bb6.png)
![New Piskel (33)](https://user-images.githubusercontent.com/77232429/106326979-0f7e3080-6286-11eb-90d0-0e91a9bb9f28.gif)

**Comment by 4ian** [comment]
Added to the website, thanks!
