### ISSUE TITLE
Lock simulation - Simulation d'écluse - Sluis simulatie - Simulazione delle chiusa

### ISSUE THREAD

**Issue by DavWai** [GDevelopApp/GDevelop-website-showcase#12]
![image](https://user-images.githubusercontent.com/62677923/106479823-0a4dfb00-64ab-11eb-8f61-d37aac1e5cf2.png)

![image](https://user-images.githubusercontent.com/62677923/106479870-15089000-64ab-11eb-9b7c-37c627cfa9ae.png)

**Lock Simulation (english, french, dutch, italian)**, by Pragmasoft asbl
Based on the technique of learning by test-error, this simulation allows to apprehend the operation of a lock.
The control panel is used to control gates, valves and lights. Explanatory messages provide a reflection in case of dangerous or inadequate operation.

The simulation allows to open all valves at the same time, which is not realistic but allows to learn the communicating vessels.

**Details**
- Simulation - educational
- French, English, Dutch, Italian
- Windows, Mac, Linux
- Free

Play in browser 
[]https://www.pragmasoft.be/carnets/geo/ecluse/html5/

Download
[]https://www.pragmasoft.be/carnets/geo/ecluse

**Comment by 4ian** [comment]
Very nice! Can you use the new form to submit your game? https://docs.google.com/forms/d/e/1FAIpQLSfjiOnkbODuPifSGuzxYY61vB5kyMWdTZSSqkJsv3H6ePRTQA/viewform?usp=sf_link

Will be helpful to add it in the showcase soon :)

**Comment by 4ian** [comment]
Added to the website. Thanks again! :)
