### ISSUE TITLE
New game for the showcase

### ISSUE THREAD

**Issue by Nathancasinillo** [GDevelopApp/GDevelop-website-showcase#4]
## Screenshots
![rsz_ss8](https://user-images.githubusercontent.com/76846157/103442982-ad85d780-4c95-11eb-9f15-ebefad4147db.png)
![ss1](https://user-images.githubusercontent.com/76846157/103442994-c1c9d480-4c95-11eb-9999-48d1775007e7.png)
![ss2](https://user-images.githubusercontent.com/76846157/103442995-c42c2e80-4c95-11eb-939f-d13c50267e30.png)
![ss5](https://user-images.githubusercontent.com/76846157/103442998-cbebd300-4c95-11eb-9c75-8566ece17ce3.png)
![ss7](https://user-images.githubusercontent.com/76846157/103443000-ce4e2d00-4c95-11eb-9434-fd7c0a22a336.png)

## Name, links and details

- Your name: Nathaniel Casinillo
- Your game name: Pixel Ball
- Description of the game in a few sentences: A ball that can switch to six colors. White, Blue, Red, Green, Orange, and Black. Every color has a different ability that you need to finish every level. Your mission is to get all the gold key and go to the gold platform to finish the level.
- Links to download, buy or play to the game: https://play.google.com/store/apps/details?id=com.makeplay.pixelball

**Comment by Oxey405** [comment]
It's cool but maybe you can make the colors less... hard, I think ?

**Comment by 4ian** [comment]
Looks good! Sorry for the delay, I'll add both of your games :)

**Comment by 4ian** [comment]
Hello again! I've made a form now to add games to the showcase, could you fill it up with your game description and images? It's here: https://docs.google.com/forms/d/e/1FAIpQLSfjiOnkbODuPifSGuzxYY61vB5kyMWdTZSSqkJsv3H6ePRTQA/viewform?usp=sf_link

Thank you! Will help me to add games to the showcase in a much faster way :)

**Comment by Nathancasinillo** [comment]
I accidentally close the issue of my Memory Tap, but I already submit a form for Memory Tap. in this link: https://docs.google.com/forms/d/e/1FAIpQLSfjiOnkbODuPifSGuzxYY61vB5kyMWdTZSSqkJsv3H6ePRTQA/viewform?usp=sf_link

Is that okay? Or I still need to make an issue for showcase here?

**Comment by 4ian** [comment]
No it's fine, the form is all that is needed - I'll soon close all the issues here as they are replaced by the form :) 
Thanks!

**Comment by 4ian** [comment]
Added to the website, thanks!
