### ISSUE TITLE
Helico - New game for the showcase

### ISSUE THREAD

**Issue by GameSomeStudio** [GDevelopApp/GDevelop-website-showcase#5]
![title](https://user-images.githubusercontent.com/77145678/103994387-fc58d300-51a7-11eb-9d61-7a3dd3006521.PNG)
![4](https://user-images.githubusercontent.com/77145678/103994365-f662f200-51a7-11eb-8e52-29f33b1f799f.png)
![1](https://user-images.githubusercontent.com/77145678/103994324-e6e3a900-51a7-11eb-9b83-4c0464537822.png)
![2](https://user-images.githubusercontent.com/77145678/103994334-eb0fc680-51a7-11eb-8466-5cf8f7579bb2.png)
![3](https://user-images.githubusercontent.com/77145678/103994357-f2cf6b00-51a7-11eb-82d7-bc2373a4a28c.png)

## Helico

HELICO is a physics-engine based indie game. Objects behavior may be differ in level repeats.
The aim of the game is to save enough people or to put out fires by helicopter, before time runs out.
At the start of the level, you can see what needs to be done to complete the task at the top right of the screen.
Different vehicles have different features.
When the episode is completed, the time remaining and the number of people rescued affect the score.
Joystick position can be adjusted.
The game can be paused and resumed at any time.
When you start the game again, you can continue from the last game or start a new game.
-Thanks for playing-

GameSome

- https://youtu.be/2a_M_LCZec4
- https://play.google.com/store/apps/details?id=com.gamesome.helicosim
- https://gamesome.itch.io/helico-rescue

**Comment by 4ian** [comment]
Very nice! I'll add it.

Good job on this game 👍

**Comment by 4ian** [comment]
Hello again! I've made a form now to add games to the showcase, could you fill it up with your game description and images? It's here: https://docs.google.com/forms/d/e/1FAIpQLSfjiOnkbODuPifSGuzxYY61vB5kyMWdTZSSqkJsv3H6ePRTQA/viewform?usp=sf_link

Thank you! Will help me add faster games to the showcase :)

**Comment by GameSomeStudio** [comment]
Thank you very much for developing this great game engine.

**Comment by 4ian** [comment]
Added to the website, thanks! :)
