### ISSUE TITLE
Cloudship, a game for the showcase

### ISSUE THREAD

**Issue by Oxey405** [GDevelopApp/GDevelop-website-showcase#6]
## Screenshots
![cloudship01](https://user-images.githubusercontent.com/61246500/104125306-24863480-5356-11eb-80b1-abf506734e04.png)
![cloudship02](https://user-images.githubusercontent.com/61246500/104125307-25b76180-5356-11eb-84f0-5e16aa2fe0ea.png)
![cloudship03](https://user-images.githubusercontent.com/61246500/104125308-25b76180-5356-11eb-9890-35fd0fd74c8f.png)

## Name, links and details

- Your name: Oxey405
- Your game name: Cloudship
- Description of the game in a few sentences: 
Cloudship is a free shoot-em-up with a rich story about a association that threatens the ecological balance 
- Links to download, buy or play to the game: https://oxey405.itch.io/cloudship

**Comment by 4ian** [comment]
Thanks for the submission! :)

**Comment by 4ian** [comment]
Hello again! I've made a form now to add games to the showcase, could you fill it up with your game description and images? It's here: https://docs.google.com/forms/d/e/1FAIpQLSfjiOnkbODuPifSGuzxYY61vB5kyMWdTZSSqkJsv3H6ePRTQA/viewform?usp=sf_link

Thank you! Will help me add faster games to the showcase :)

**Comment by Oxey405** [comment]
Thank you 4ian ! I published an answer on the form and I reposted one because I forgot to put the game banner.

**Comment by 4ian** [comment]
Added to the website, thanks!
