### ISSUE TITLE
New game for the showcase

### ISSUE THREAD

**Issue by alfonsobcp** [GDevelopApp/GDevelop-website-showcase#7]
## Screenshots

![MetroLinea1-Portada](https://user-images.githubusercontent.com/67919721/104355836-da758e00-54d0-11eb-8247-9011d044f52d.jpg)
![MetroLinea1-2](https://user-images.githubusercontent.com/67919721/104355888-ec573100-54d0-11eb-8b9d-ddee20d10eb9.jpg)
![MetroLinea1-3](https://user-images.githubusercontent.com/67919721/104355921-f37e3f00-54d0-11eb-88e6-b6d8c45c7238.png)
![MetroLinea1-7](https://user-images.githubusercontent.com/67919721/104355937-f842f300-54d0-11eb-8293-8d14229a094f.jpg)
![MetroLinea1-5](https://user-images.githubusercontent.com/67919721/104355949-fb3de380-54d0-11eb-907b-0c58c8213112.png)

## Name, links and details

- Your name: Alfonso Cortés
- Your game name: Metro Línea 1
- Description of the game in a few sentences: La gráfica de esta app está basada en las ilustraciones de Emmanuel Peña, quien nos regala todo un carnaval de insólitas situaciones y fantásticos personajes que transitan en los vagones del metro. Arma los rompecabezas y encuentra las disparatadas aventuras que los pasajeros viven en el metro de la Ciudad de México.
-
- Links to download, buy or play to the game: Google Play: 

https://play.google.com/store/apps/details?id=com.edim.metrol1&hl=es

**Comment by 4ian** [comment]
Looks very nice! I've unfortunately not been able to try the game on my device: 
![image](https://user-images.githubusercontent.com/1280130/105609813-a8eba500-5da3-11eb-8125-24cd2c7c3539.png)

But I'll be happy to add it in the showcase :)

**Comment by alfonsobcp** [comment]
Hi, the app is for android, not for ios or windows.

What is your operative system? wich version of android?

Thank´s for comment.

**Comment by 4ian** [comment]
Hello again! I've made a form now to add games to the showcase, could you fill it up with your game description and images? It's here: https://docs.google.com/forms/d/e/1FAIpQLSfjiOnkbODuPifSGuzxYY61vB5kyMWdTZSSqkJsv3H6ePRTQA/viewform?usp=sf_link

Thank you! Will help me add faster games to the showcase :) 

For the game, I'm using Android 11, but I visited the Play Store from my computer. I have to try directly on my phone to see if it's better :)

**Comment by Bouh** [comment]
I can't install the game too, from France, with android 9.

**Comment by alfonsobcp** [comment]
Hi. The game is for android, from your phone or tablet you have to open the
app Google Play, find Metro Linea 1, the cost of the game is $2 dollars.

**Comment by alfonsobcp** [comment]
Yes, try directly for your phone or tablet android: Open de app Google
Play, find Metro Linea 1, the cost of the game is $2 dollars.

**Comment by 4ian** [comment]
Added to the website, thanks! :)

**Comment by alfonsobcp** [comment]
It´s amazing, thanks.
