### ISSUE TITLE
New game for the showcase

### ISSUE THREAD

**Issue by nikolaign** [GDevelopApp/GDevelop-website-showcase#9]
## Screenshots

![042D3638-FCB8-4439-87AB-DDAB517DD254](https://user-images.githubusercontent.com/26126806/105278425-bc312180-5ba5-11eb-9c9d-b480496f6709.png)
![A9F207E6-8B1B-41D2-906B-09B735822BE2](https://user-images.githubusercontent.com/26126806/105278428-bd624e80-5ba5-11eb-9655-7d94c45d101d.png)
![DB49B04F-31E7-437E-86FA-5BFD8222CAC8](https://user-images.githubusercontent.com/26126806/105278479-dec33a80-5ba5-11eb-9ce9-783532bbbd68.jpeg)

## Name, links, and details

- Name: Seraphi
- Game name: Polytope Episode One: Tesseract
- Description of the game: 
Platform with a story in a perspective of a cube. The story is about a cube (which you control), the cube’s monologs, and realizing that player (you) controls the cube.

- Links to download, buy or play the game:
nikolaign.itch.io/polytope

**Comment by 4ian** [comment]
Interesting game! Nice work on this, I'll add it to the showcase :)

**Comment by nikolaign** [comment]
Oh that means a lot coming from you, thank you very much!

**Comment by 4ian** [comment]
Hello again! I've made a form now to add games to the showcase, could you fill it up with your game description and images? It's here: https://docs.google.com/forms/d/e/1FAIpQLSfjiOnkbODuPifSGuzxYY61vB5kyMWdTZSSqkJsv3H6ePRTQA/viewform?usp=sf_link

Thank you! Will help me add faster games to the showcase :)

**Comment by 4ian** [comment]
Added to the website, thanks! :)
